# Generated by Django 4.2.8 on 2024-01-11 04:55

import announcement.models.helpers.rename_announcement_material
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_title', models.CharField(max_length=200)),
                ('ann_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ann_filepath', models.FileField(upload_to=announcement.models.helpers.rename_announcement_material.rename_announcement_material)),
            ],
        ),
    ]
