# Generated by Django 4.2.8 on 2024-01-11 04:49

import assignments.models.helper.rename_assignment
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('academics', '0005_subjectenrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_title', models.CharField(max_length=200)),
                ('as_description', models.TextField()),
                ('as_filepath', models.FileField(upload_to=assignments.models.helper.rename_assignment.rename_assignment_material)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_trans_path', models.FileField(upload_to=assignments.models.helper.rename_assignment.rename_assignment_transaction)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmenttransactions', to='assignments.assignment')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submittedby', to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_trans_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmentgradings', to='assignments.assignmenttransaction')),
            ],
        ),
    ]
