# Generated by Django 4.2.8 on 2024-01-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignmenttransactiontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.TextField()),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmenttexts', to='assignments.assignment')),
            ],
        ),
        migrations.DeleteModel(
            name='AssignmentTransactionText',
        ),
    ]
