# Generated by Django 4.2.8 on 2024-01-10 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='classrecordsummary',
            name='record_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classrecordtexts', to='academics.classrecord'),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrecords', to='academics.subject'),
        ),
    ]
