# Generated by Django 4.2.8 on 2024-01-10 00:30

import academics.models.helper.rename_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_subjectmaterial_sub_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='audio_path',
            field=models.FileField(upload_to=academics.models.helper.rename_file.rename_class_record),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='sub_filepath',
            field=models.FileField(upload_to=academics.models.helper.rename_file.rename_subject_material),
        ),
    ]
