# Generated by Django 4.2.8 on 2024-01-11 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_classrecordsummary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmaterialtext',
            name='status',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
