# Generated by Django 4.2.8 on 2024-01-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('academics', '0007_subjectmaterialtext_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='users.teacher'),
        ),
    ]
